public class Opciones extends javax.swing.JFrame {
    
    crearCliente cc2 = new crearCliente();
    verClientes vc2 = new verClientes();
    Deposito d2 = new Deposito();
    Transferencia t2 = new Transferencia();
    Servicios s2 = new Servicios();
    Historial h2 = new Historial();
    crearCuenta cc3 = new crearCuenta();

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        
        initComponents();
        initComponents2();
        this.setTitle("Menu");
        
    }
    
    public void initComponents2(){
    
        setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btt_historial = new javax.swing.JButton();
        btt_crearCliente = new javax.swing.JButton();
        btt_verClientes = new javax.swing.JButton();
        btt_transferencia = new javax.swing.JButton();
        btt_deposito = new javax.swing.JButton();
        btt_crearCuenta = new javax.swing.JButton();
        btt_servicios1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(592, 405));
        jPanel1.setLayout(null);

        btt_historial.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_historial.setText("Historial");
        btt_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_historialActionPerformed(evt);
            }
        });
        jPanel1.add(btt_historial);
        btt_historial.setBounds(220, 310, 150, 40);

        btt_crearCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_crearCliente.setText("Crear Cliente");
        btt_crearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_crearClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btt_crearCliente);
        btt_crearCliente.setBounds(90, 70, 150, 40);

        btt_verClientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_verClientes.setText("Ver Clientes");
        btt_verClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_verClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btt_verClientes);
        btt_verClientes.setBounds(360, 70, 150, 40);

        btt_transferencia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_transferencia.setText("Transferencia");
        btt_transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_transferenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btt_transferencia);
        btt_transferencia.setBounds(360, 230, 150, 40);

        btt_deposito.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_deposito.setText("Deposito");
        btt_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_depositoActionPerformed(evt);
            }
        });
        jPanel1.add(btt_deposito);
        btt_deposito.setBounds(360, 150, 150, 40);

        btt_crearCuenta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_crearCuenta.setText("Crear Cuenta");
        btt_crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_crearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btt_crearCuenta);
        btt_crearCuenta.setBounds(90, 150, 150, 40);

        btt_servicios1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_servicios1.setText("Servicios");
        btt_servicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_servicios1ActionPerformed(evt);
            }
        });
        jPanel1.add(btt_servicios1);
        btt_servicios1.setBounds(90, 230, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_historialActionPerformed
        
        h2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btt_historialActionPerformed

    private void btt_transferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_transferenciaActionPerformed
        
        t2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btt_transferenciaActionPerformed

    private void btt_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_depositoActionPerformed
        
        d2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btt_depositoActionPerformed

    private void btt_crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_crearCuentaActionPerformed
        
        cc3.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btt_crearCuentaActionPerformed

    private void btt_verClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_verClientesActionPerformed
        
        vc2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btt_verClientesActionPerformed

    private void btt_crearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_crearClienteActionPerformed
        
        cc2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btt_crearClienteActionPerformed

    private void btt_servicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_servicios1ActionPerformed
        
        s2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btt_servicios1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_crearCliente;
    private javax.swing.JButton btt_crearCuenta;
    private javax.swing.JButton btt_deposito;
    private javax.swing.JButton btt_historial;
    private javax.swing.JButton btt_servicios1;
    private javax.swing.JButton btt_transferencia;
    private javax.swing.JButton btt_verClientes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}