public class Transferencia extends javax.swing.JFrame {

    /**
     * Creates new form Transferencia
     */
    public Transferencia() {
        
        initComponents();
        initComponents2();
        this.setTitle("Transferencia entre cuentas");
        
    }
    
    public void initComponents2(){
    
        setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbx_cuentaOrigen = new javax.swing.JComboBox<>();
        cbx_cuentaDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_montoTrans = new javax.swing.JTextField();
        btt_aceptar = new javax.swing.JButton();
        btt_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 450));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Cuenta de origen");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 30, 140, 30);

        cbx_cuentaOrigen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(cbx_cuentaOrigen);
        cbx_cuentaOrigen.setBounds(40, 60, 310, 30);

        cbx_cuentaDestino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbx_cuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cuentaDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(cbx_cuentaDestino);
        cbx_cuentaDestino.setBounds(40, 200, 310, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Cuenta de destino");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 170, 150, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Monto");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 300, 50, 30);

        txt_montoTrans.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txt_montoTrans);
        txt_montoTrans.setBounds(40, 330, 310, 30);

        btt_aceptar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_aceptar.setText("Aceptar");
        btt_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btt_aceptar);
        btt_aceptar.setBounds(230, 390, 110, 30);

        btt_regresar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_regresar.setText("Regresar");
        btt_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(btt_regresar);
        btt_regresar.setBounds(50, 390, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_regresarActionPerformed
        
        this.setVisible(false);
        new Opciones().setVisible(true);        
        
    }//GEN-LAST:event_btt_regresarActionPerformed

    private void btt_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_aceptarActionPerformed

    private void cbx_cuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cuentaDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_aceptar;
    private javax.swing.JButton btt_regresar;
    private javax.swing.JComboBox<String> cbx_cuentaDestino;
    private javax.swing.JComboBox<String> cbx_cuentaOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_montoTrans;
    // End of variables declaration//GEN-END:variables
}
