import javax.swing.table.DefaultTableModel;


public class verClientes extends javax.swing.JFrame {

    /**
     * Creates new form verClientes
     */
    public verClientes() {
        
        initComponents();
        initComponents2();
        this.setTitle("Ver clientes");
        
        crearCliente vt = new crearCliente();
        
        String[][] matriz = new String[vt.listaClientes.length][3];
        for(int i=0; i<vt.listaClientes.length;i++){
            if(vt.listaClientes[i]!=null){
                matriz[i][0]=String.valueOf(vt.listaClientes[i].cui);
                matriz[i][1]=vt.listaClientes[i].nombre;
                matriz[i][2]=vt.listaClientes[i].apellido;
            }
        }
        
        String[] encabezado = {"CUI","Nombre","Apellido"};
        tabla_clientes.setModel(new DefaultTableModel(matriz,encabezado));
        
    }
    
    public void initComponents2(){
    
        setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_clientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_cui = new javax.swing.JTextField();
        btt_buscarCuentas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btt_regresar = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 450));
        jPanel1.setLayout(null);

        tabla_clientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CUI", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(tabla_clientes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(26, 19, 642, 160);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("CUI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 240, 30, 20);

        txt_cui.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txt_cui);
        txt_cui.setBounds(30, 260, 290, 30);

        btt_buscarCuentas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_buscarCuentas.setText("Buscar cuentas asociadas");
        btt_buscarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_buscarCuentasActionPerformed(evt);
            }
        });
        jPanel1.add(btt_buscarCuentas);
        btt_buscarCuentas.setBounds(400, 260, 260, 31);

        jTable3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Cuentas asociadas"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(30, 310, 110, 120);

        btt_regresar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btt_regresar.setText("Regresar");
        btt_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(btt_regresar);
        btt_regresar.setBounds(470, 380, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_regresarActionPerformed
        
        this.setVisible(false);
        new Opciones().setVisible(true);        
        
    }//GEN-LAST:event_btt_regresarActionPerformed

    private void btt_buscarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_buscarCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_buscarCuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_buscarCuentas;
    private javax.swing.JButton btt_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tabla_clientes;
    private javax.swing.JTextField txt_cui;
    // End of variables declaration//GEN-END:variables
}
